const CLIENT_ID="68654a51-90fc-4126-b19f-c3b9c59fa9ea";
const REDIRECT_URI="https://seanriggs.github.io/sickle-scythe-business-tracker/";
const SCOPES="openid profile offline_access User.Read Files.ReadWrite.AppFolder";
const AUTH="https://login.microsoftonline.com/common/oauth2/v2.0";
const GRAPH="https://graph.microsoft.com/v1.0";
const FILE="business-data.json";
const statusEl=document.querySelector("#status"),messageEl=document.querySelector("#message"),previewEl=document.querySelector("#preview");
function show(x){messageEl.textContent=x} function b64(bytes){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/," ").trim()}
async function hash(s){return new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s)))}
function random(){const a=new Uint8Array(64);crypto.getRandomValues(a);return b64(a)}
function token(){try{return JSON.parse(localStorage.getItem("ss_tokens")||"null")}catch{return null}}
function setToken(t){localStorage.setItem("ss_tokens",JSON.stringify({...t,expires_at:Date.now()+(Number(t.expires_in)||3600)*1000}));state()}
function state(){const t=token();statusEl.textContent=t?"Microsoft account connected":"Not signed in"}
async function signIn(){const verifier=random(),challenge=b64(await hash(verifier)),stateValue=random();sessionStorage.setItem("pkce_verifier",verifier);sessionStorage.setItem("oauth_state",stateValue);const q=new URLSearchParams({client_id:CLIENT_ID,response_type:"code",redirect_uri:REDIRECT_URI,response_mode:"query",scope:SCOPES,state:stateValue,code_challenge:challenge,code_challenge_method:"S256"});location.href=`${AUTH}/authorize?${q}`}
async function callback(){const q=new URLSearchParams(location.search),code=q.get("code");if(!code)return; if(q.get("state")!==sessionStorage.getItem("oauth_state"))throw new Error("Sign-in state validation failed.");const body=new URLSearchParams({client_id:CLIENT_ID,grant_type:"authorization_code",code,redirect_uri:REDIRECT_URI,code_verifier:sessionStorage.getItem("pkce_verifier")});const r=await fetch(`${AUTH}/token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});const data=await r.json();if(!r.ok)throw new Error(data.error_description||data.error||"Token exchange failed");setToken(data);history.replaceState({},document.title,REDIRECT_URI);show("Microsoft sign-in succeeded. Test Save, then Load.")}
async function accessToken(){let t=token();if(!t)throw new Error("Sign in first.");if(Date.now()<t.expires_at-60000)return t.access_token;if(!t.refresh_token)throw new Error("Session expired. Sign in again.");const body=new URLSearchParams({client_id:CLIENT_ID,grant_type:"refresh_token",refresh_token:t.refresh_token,redirect_uri:REDIRECT_URI,scope:SCOPES});const r=await fetch(`${AUTH}/token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});const data=await r.json();if(!r.ok)throw new Error(data.error_description||"Refresh failed");setToken({...t,...data});return data.access_token}
async function graph(path,options={}){const t=await accessToken();const r=await fetch(GRAPH+path,{...options,headers:{Authorization:`Bearer ${t}`,...(options.headers||{})}});if(!r.ok)throw new Error(`${r.status}: ${await r.text()}`);return r}
async function save(){try{show("Saving to OneDrive...");const cached=localStorage.getItem("sickle-scythe-tracker-v3");const data=cached?JSON.parse(cached):{schemaVersion:1,orders:[],sales:[],payments:[],expenses:[],claims:[],adjustments:[],history:[]};data.cloudUpdatedAt=new Date().toISOString();await graph(`/me/drive/special/approot:/${FILE}:/content`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(data,null,2)});previewEl.textContent=JSON.stringify(data,null,2);show("Cloud database saved successfully.")}catch(e){show("Save failed: "+e.message)}}
async function load(){try{show("Loading from OneDrive...");const r=await graph(`/me/drive/special/approot:/${FILE}:/content`);const data=await r.json();previewEl.textContent=JSON.stringify(data,null,2);localStorage.setItem("sickle-scythe-cloud-cache",JSON.stringify(data));show("Cloud database loaded successfully.")}catch(e){show(String(e).includes("404")?"No cloud database exists yet. Save one first.":"Load failed: "+e.message)}}
function signOut(){localStorage.removeItem("ss_tokens");state();show("Signed out locally.")}
document.querySelector("#signin").addEventListener("click",()=>signIn().catch(e=>show("Sign-in failed: "+e.message)));document.querySelector("#load").addEventListener("click",load);document.querySelector("#save").addEventListener("click",save);document.querySelector("#signout").addEventListener("click",signOut);
state();callback().catch(e=>show("Sign-in callback failed: "+e.message));
