const CLIENT_ID="68654a51-90fc-4126-b19f-c3b9c59fa9ea",REDIRECT_URI="https://seanriggs.github.io/sickle-scythe-business-tracker/",AUTH="https://login.microsoftonline.com/common/oauth2/v2.0",GRAPH="https://graph.microsoft.com/v1.0",SCOPES="openid profile offline_access User.Read Files.ReadWrite.AppFolder",CLOUD_FILE="business-data.json",LOCAL="ss-v4-db",BUILD="5.2";
const PRODUCTS=[{id:'p1',name:'vSeeBox V6 Plus',maker:'vSeeBox',cost:200,typical:265,retail:389},{id:'p2',name:'vSeeBox V6 Replacement Remote',maker:'vSeeBox',cost:10,typical:15,retail:19.99},{id:'p3',name:'We2uSat K3+',maker:'We2uSat',cost:148,typical:225,retail:329},{id:'p4',name:'We2uSat P6 Mini',maker:'We2uSat',cost:160,typical:245,retail:335}],PAYS=['Cash','Venmo','PayPal','Zelle','Credit Card','Check','Bank Transfer','Other'],NAV=['Dashboard','Products','Purchase Orders','Receivables','Sales & Payments','Customers','Expenses','Warranty','Reports','Needs Review','Data Health','History','Settings'];
const EMPTY={schemaVersion:4,orders:[],sales:[],payments:[],expenses:[],claims:[],adjustments:[],history:[],updatedAt:null,settings:{lowStock:{}}};let db=load(),page='Dashboard',syncTimer,syncState='Saved locally',globalQuery='',deferredInstall=null;
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0)),today=()=>new Date().toISOString().slice(0,10),uid=p=>p+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),pname=id=>PRODUCTS.find(p=>p.id===id)?.name||'Unknown';
function load(){try{let x={...EMPTY,...JSON.parse(localStorage.getItem(LOCAL)||'{}')};x.settings=x.settings||{lowStock:{}};x.settings.lowStock=x.settings.lowStock||{};return x}catch{return structuredClone(EMPTY)}} function audit(a,d){db.history.unshift({id:uid('H'),date:new Date().toISOString(),action:a,detail:d});db.history=db.history.slice(0,1000)} function saveLocal(a,d){if(a)audit(a,d);db.updatedAt=new Date().toISOString();localStorage.setItem(LOCAL,JSON.stringify(db));syncState=token()?'Waiting to sync':'Saved locally';render();if(token()){clearTimeout(syncTimer);syncTimer=setTimeout(()=>cloudSave(true),1000)}}
function inventory(){return PRODUCTS.map(p=>{let rec=db.orders.filter(o=>!o.cancelled).flatMap(o=>o.lines||[]).filter(l=>l.productId===p.id).reduce((n,l)=>n+Number(l.received||0),0),sold=db.sales.filter(s=>!s.voided&&s.productId===p.id).reduce((n,s)=>n+Number(s.qty),0),war=db.claims.filter(c=>!c.voided&&c.productId===p.id&&c.replacementSent).reduce((n,c)=>n+Number(c.qty),0),adj=db.adjustments.filter(a=>!a.voided&&a.productId===p.id).reduce((n,a)=>n+Number(a.qty),0);return {...p,onHand:rec-sold-war+adj,received:rec,sold,war}})}
function totals(){let revenue=db.sales.filter(s=>!s.voided).reduce((n,s)=>n+s.qty*s.unitPrice,0),paid=db.payments.filter(p=>!p.voided).reduce((n,p)=>n+p.amount,0),expenses=db.expenses.filter(e=>!e.voided).reduce((n,e)=>n+e.amount,0),credit=db.claims.filter(c=>!c.voided).reduce((n,c)=>n+Math.max(0,c.approvedCredit-c.appliedCredit),0),inv=inventory();return{revenue,paid,expenses,ar:Math.max(0,revenue-paid),credit,onHand:inv.reduce((n,p)=>n+p.onHand,0),invValue:inv.reduce((n,p)=>n+Math.max(0,p.onHand)*p.cost,0)}}
function token(){try{let t=JSON.parse(localStorage.getItem('ss_tokens')||'null');return t&&(t.access_token||t.refresh_token)?t:null}catch{return null}} function setToken(t){localStorage.setItem('ss_tokens',JSON.stringify({...t,expires_at:Date.now()+(+t.expires_in||3600)*1000}))} function b64(a){return btoa(String.fromCharCode(...a)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')} async function signIn(){let v=b64(crypto.getRandomValues(new Uint8Array(64))),c=b64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)))),s=b64(crypto.getRandomValues(new Uint8Array(32)));sessionStorage.pkce=v;sessionStorage.state=s;location.href=AUTH+'/authorize?'+new URLSearchParams({client_id:CLIENT_ID,response_type:'code',redirect_uri:REDIRECT_URI,response_mode:'query',scope:SCOPES,state:s,code_challenge:c,code_challenge_method:'S256'})} async function callback(){let q=new URLSearchParams(location.search),code=q.get('code');if(!code)return;if(q.get('state')!==sessionStorage.state)throw Error('State validation failed');let r=await fetch(AUTH+'/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:CLIENT_ID,grant_type:'authorization_code',code,redirect_uri:REDIRECT_URI,code_verifier:sessionStorage.pkce})}),x=await r.json();if(!r.ok)throw Error(x.error_description);setToken(x);history.replaceState({},'',REDIRECT_URI);await firstSync()}
async function access(){let t=token();if(!t)throw Error('Sign in first');if(Date.now()<t.expires_at-60000)return t.access_token;let r=await fetch(AUTH+'/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:CLIENT_ID,grant_type:'refresh_token',refresh_token:t.refresh_token,redirect_uri:REDIRECT_URI,scope:SCOPES})}),x=await r.json();if(!r.ok){localStorage.removeItem('ss_tokens');render();throw Error('Microsoft session expired. Select Reconnect Microsoft Account.')}setToken({...t,...x});return x.access_token} async function graph(path,opt={}){let r=await fetch(GRAPH+path,{...opt,headers:{Authorization:'Bearer '+await access(),...(opt.headers||{})}});if(!r.ok)throw Object.assign(Error(await r.text()),{status:r.status});return r}
async function cloudLoad(silent=false){try{syncState='Loading cloud';render();let c=await(await graph('/me/drive/special/approot:/'+CLOUD_FILE+':/content')).json();db={...EMPTY,...c};localStorage.setItem(LOCAL,JSON.stringify(db));syncState='Cloud current';if(!silent)alert('Loaded from OneDrive');render();return true}catch(e){if(e.status===404)return false;if(!silent)alert('Load failed: '+e.message);return false}} async function cloudSave(silent=false){try{syncState='Saving to cloud';render();await graph('/me/drive/special/approot:/'+CLOUD_FILE+':/content',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(db)});syncState='Cloud saved';if(!silent)alert('Saved to OneDrive');render();return true}catch(e){if(!silent)alert('Save failed: '+e.message);return false}} async function firstSync(){let ok=await cloudLoad(true);if(!ok)await cloudSave(true);render()}
function shell(body){let connected=!!token();return `<div class="shell"><aside class="side"><div class="brand"><img src="${brandingLogo()}"><div><b>Sickle & Scythe</b><div class="muted">Business Tracker v5.2</div></div></div><div class="nav">${NAV.map(n=>`<button class="${page===n?'active':''}" onclick="go('${n}')">${n}</button>`).join('')}</div></aside><main class="main"><header class="top"><div><h2>${page}</h2></div><div class="top-tools"><input class="global-search" value="${globalQuery.replace(/"/g,'&quot;')}" oninput="setGlobalSearch(this.value)" placeholder="Search customer, invoice, PO, expense..."><span class="status ${connected?'':'warn'}">${connected?syncState:'Local only'}</span></div></header><div class="content"><div id="search-host">${universalSearch()}</div>${body}</div></main></div>`}

function customerNames(){return [...new Set([...db.sales.map(s=>s.customer),...db.claims.map(c=>c.customer)].filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function customerField(value=''){return `<label class="field"><span>Customer${help('Customer')}</span><input name="customer" list="customer-list" autocomplete="off" value="${String(value).replace(/"/g,'&quot;')}" placeholder="Start typing a customer name"><datalist id="customer-list">${customerNames().map(n=>`<option value="${n.replace(/"/g,'&quot;')}"></option>`).join('')}</datalist></label>`}

function metric(l,v){return `<div class="card metric"><small>${l}</small><strong>${v}</strong></div>`} function field(l,n,t='text',v=''){let step=t==='number'?' step="0.01" inputmode="decimal"':'';return `<label class="field"><span>${l}${help(l)}</span><input name="${n}" type="${t}"${step} value="${v}"></label>`} function select(l,n,opts){return `<label class="field"><span>${l}${help(l)}</span><select name="${n}">${opts.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select></label>`} function empty(a){return a.length?'':'<p class="muted">No records yet.</p>'}

let arFilter='Priority',selectedCustomer=null;
function invoiceRows(){return db.sales.filter(s=>!s.voided).map(s=>{let paid=db.payments.filter(p=>!p.voided&&p.saleId===s.id).reduce((n,p)=>n+Number(p.amount||0),0),total=Number(s.qty||0)*Number(s.unitPrice||0),balance=total-paid,date=s.date?new Date(s.date+'T00:00:00'):null,age=date&&!isNaN(date)?Math.floor((Date.now()-date.getTime())/86400000):null,status=balance<-.009?'Credit':balance>.009?'Due':'Paid',bucket=age===null?'Unknown Date':age<=30?'0-30 Days':age<=60?'31-60 Days':age<=90?'61-90 Days':'90+ Days';return{...s,total,paid,balance,age,status,bucket}})}
function arPriority(x){return x.status==='Credit'?0:x.status==='Due'?1:2}
function receivablesView(){let rows=invoiceRows().filter(x=>arFilter==='Priority'||arFilter==='All'||x.status===arFilter||x.bucket===arFilter);rows.sort((a,b)=>arPriority(a)-arPriority(b)||(a.status==='Credit'?a.balance-b.balance:b.balance-a.balance)||((a.age||-1)<(b.age||-1)?1:-1));let opts=['Priority','All','Due','Credit','Paid','0-30 Days','31-60 Days','61-90 Days','90+ Days','Unknown Date'];return `<div class="card hero"><h1>Receivables Workspace</h1><p class="muted">Credits and balances requiring attention appear first.</p><div class="actions">${opts.map(x=>`<button class="${arFilter===x?'active':''}" onclick="setARFilter('${x}')">${x}</button>`).join('')}</div></div><div class="card">${empty(rows)}${rows.map(x=>`<div class="row"><div><b>${x.customer} · ${x.id}</b><p>${pname(x.productId)} · ${x.date||'Unknown date'} · ${x.bucket}</p></div><div class="actions"><span class="tag">${x.status==='Credit'?money(Math.abs(x.balance))+' credit':x.status==='Due'?money(x.balance)+' due':'Paid'}</span><button onclick="openCustomer('${escAttr(x.customer)}')">Customer</button>${x.status==='Credit'?`<button class="primary" onclick="manageCredit('${escAttr(x.customer)}')">Manage Credit</button>`:''}${x.balance>0?`<button onclick="createInvoice('${x.id}')">Create Invoice / PDF</button><button class="primary" onclick="pay('${x.id}',${x.balance})">Payment</button>`:''}</div></div>`).join('')}</div>`}
function setARFilter(x){arFilter=x;render()} function escAttr(x){return String(x).replace(/'/g,"\\'")}
function openCustomer(name){selectedCustomer=name;page='Customers';render()}

function creditLedger(name){let ids=new Set(db.sales.filter(s=>s.customer===name).map(s=>s.id)),rows=db.payments.filter(p=>!p.voided&&ids.has(p.saleId)&&(p.creditAction||p.method==='Customer Credit'||p.method==='Credit Applied'||p.method==='Customer Refund')).map(p=>({date:p.date||'Unknown date',label:p.method||p.creditAction,amount:Number(p.amount||0),source:p.creditSourceInvoice||p.saleId,target:p.creditTargetInvoice||''}));return `<div class="card"><h3>Credit Ledger</h3><p class="muted">Tracks overpayments, credit applications, refunds, and retained customer credits.</p>${empty(rows)}${rows.map(x=>`<div class="row"><div><b>${x.label}</b><p>${x.date} · ${x.source}${x.target?' → '+x.target:''}</p></div><strong>${x.amount>=0?'+':''}${money(x.amount)}</strong></div>`).join('')}<div class="row"><b>Available invoice credit</b><strong>${money(creditInvoices(name).reduce((n,x)=>n+Math.abs(x.balance),0))}</strong></div></div>`}

function customerDetail(name){let ss=invoiceRows().filter(x=>x.customer===name),ids=ss.map(x=>x.id),pp=db.payments.filter(p=>!p.voided&&ids.includes(p.saleId)),cc=db.claims.filter(c=>!c.voided&&c.customer===name),inv=ss.reduce((n,x)=>n+x.total,0),paid=pp.reduce((n,x)=>n+Number(x.amount||0),0);return `<div class="card hero"><div class="row"><div><h2>${name}</h2><p>${ss.length} invoices · ${unitCount(ss)} units purchased · ${pp.length} payments · ${cc.length} warranty claims</p></div>${inv-paid<0?`<button class="primary" onclick="manageCredit('${escAttr(name)}')">Manage Credit</button>`:''}<button onclick="closeCustomer()">Back to Customers</button></div><div class="grid g3">${metric('Invoiced',money(inv))}${metric('Paid',money(paid))}${metric(inv-paid<0?'Customer Credit':'Balance Due',money(Math.abs(inv-paid)))}</div></div>${creditLedger(name)}<div class="grid g2"><div class="card"><h3>Invoices</h3>${empty(ss)}${ss.map(x=>`<div class="row"><div><b>${x.id}</b><p>${x.date||'Unknown date'} · ${x.bucket}</p></div><span class="tag">${x.status==='Credit'?money(Math.abs(x.balance))+' credit':money(x.balance)+' due'}</span></div>`).join('')}</div><div class="card"><h3>Payments</h3>${empty(pp)}${pp.map(x=>`<div class="row"><div><b>${x.method||'Unknown'}</b><p>${x.date||'Unknown date'} · ${x.saleId}</p></div><strong>${money(x.amount)}</strong></div>`).join('')}</div></div><div class="card"><h3>Customer Notes & Collections</h3><p>${customerMeta(name).notes||'No customer notes.'}</p><div class="actions">${(customerMeta(name).tags||[]).map(x=>`<span class="tag">${x}</span>`).join('')}<button onclick="editCustomerNotes('${escAttr(name)}')">Edit Notes / Tags</button><button onclick="addCollectionNote('${escAttr(name)}')">Add Collection Note</button></div>${(customerMeta(name).collections||[]).map(x=>`<div class="row"><div><b>${x.method}</b><p>${x.date} · ${x.note}</p></div></div>`).join('')}${attachmentsView('customer',name)}</div><div class="card"><h3>Warranty</h3>${empty(cc)}${cc.map(x=>`<div class="row"><div><b>${pname(x.productId)}</b><p>${x.status} · ${x.date||'Unknown date'}</p></div><span>${money(x.approvedCredit||0)} approved</span></div>`).join('')}</div>`}
function closeCustomer(){selectedCustomer=null;render()}
function reviewRows(){return (db.reviewQueue||[]).filter(x=>!x.resolved&&!x.ignored)}
function editReview(i){let rows=db.reviewQueue||[],x=rows[i];if(!x)return;let linked=x.type==='sale'?db.sales.find(s=>s.sourceRow===x.row):x.type==='warranty'?db.claims.find(c=>c.imported):null;if(x.type==='sale'&&linked){let d=prompt('Enter sale date (YYYY-MM-DD)',linked.date||'');if(d===null)return;linked.date=d;x.resolution='Sale date set to '+d}else if(x.type==='warranty'&&linked){let d=prompt('Enter warranty date (YYYY-MM-DD)',linked.date||'');if(d===null)return;linked.date=d;x.resolution='Warranty date set to '+d}else{x.resolution=prompt('Resolution note',x.resolution||'')||''}x.resolved=true;x.resolvedAt=new Date().toISOString();saveLocal('Review item resolved',(x.type||'record')+' row '+(x.row||'n/a')+' · '+x.resolution)}
function approveUnknown(i){let x=db.reviewQueue[i];x.resolved=true;x.resolution='Approved with unknown historical value';x.resolvedAt=new Date().toISOString();saveLocal('Review item approved',(x.type||'record')+' row '+(x.row||'n/a'))}
function ignoreReview(i){let reason=prompt('Reason for ignoring this review item');if(!reason)return;let x=db.reviewQueue[i];x.ignored=true;x.resolution=reason;x.resolvedAt=new Date().toISOString();saveLocal('Review item ignored',(x.type||'record')+' row '+(x.row||'n/a')+' · '+reason)}

function reviewRecord(x){if(x.type==='sale')return db.sales.find(s=>s.sourceRow===x.row);if(x.type==='warranty')return db.claims.find(c=>c.imported&&!c.voided);if(x.type==='inventory')return db.orders.find(o=>o.sourceRow===x.row);return null}
function reviewTitle(x){if(x.type==='sale'&&/missing sale date/i.test(x.issue||''))return 'Sale Date Missing';if(x.type==='sale'&&/zero or negative units/i.test(x.issue||''))return 'Sale Quantity Needs Review';if(x.type==='warranty')return 'Warranty Date Needs Confirmation';if(x.type==='inventory')return 'Purchase Date Missing';return 'Record Needs Review'}
function reviewDetails(x){let r=reviewRecord(x);if(x.type==='sale')return [{label:'Customer',value:r?.customer||x.customer||'Unknown'},{label:'Invoice',value:r?.id||'Imported sale'},{label:'Product',value:r?pname(r.productId):'Unknown'},{label:'Quantity',value:r?.qty??'Unknown'},{label:'Unit Price',value:r?money(r.unitPrice):'Unknown'},{label:'Current Date',value:r?.date||'Not recorded'},{label:'Why this appears',value:x.issue||'Imported data needs confirmation'}];if(x.type==='warranty')return [{label:'Customer',value:r?.customer||x.customer||'Unknown'},{label:'Warranty Claim',value:r?.id||'Imported warranty claim'},{label:'Product',value:r?pname(r.productId):'Unknown'},{label:'Current Date',value:r?.date||'Not recorded'},{label:'Issue',value:r?.issue||x.issue||'Needs confirmation'}];if(x.type==='inventory')return [{label:'Purchase Order',value:r?.id||'Imported purchase order'},{label:'Manufacturer',value:r?.maker||'Unknown'},{label:'Current Date',value:r?.eta||'Not recorded'},{label:'Why this appears',value:x.issue||'Imported data needs confirmation'}];return [{label:'Details',value:x.issue||'Review required'}]}
function toggleReview(i){let el=document.querySelector('#review-details-'+i),btn=document.querySelector('#review-toggle-'+i);if(!el)return;let open=el.hidden;el.hidden=!open;if(btn){btn.textContent=open?'▾':'▸';btn.setAttribute('aria-expanded',String(open))}}
function reviewStatusFilter(mode){db.settings=db.settings||{};db.settings.reviewDisplay=mode;render()}

function needsReviewView(){let all=db.reviewQueue||[],mode=db.settings?.reviewDisplay||'Active',rows=mode==='Active'?all.filter(x=>!x.resolved&&!x.ignored):mode==='Resolved'?all.filter(x=>x.resolved||x.ignored):all;return `<div class="card hero"><h1>Needs Review</h1><p class="muted">${reviewRows().length} active · ${all.length-reviewRows().length} resolved or ignored</p><div class="actions"><button class="${mode==='Active'?'active':''}" onclick="reviewStatusFilter('Active')">Active</button><button class="${mode==='Resolved'?'active':''}" onclick="reviewStatusFilter('Resolved')">Resolved / Ignored</button><button class="${mode==='All'?'active':''}" onclick="reviewStatusFilter('All')">All</button></div></div><div class="card">${empty(rows)}${rows.map(x=>{let i=all.indexOf(x),details=reviewDetails(x),closed=x.resolved||x.ignored;return `<div class="review-item"><div class="review-summary"><button id="review-toggle-${i}" class="disclosure" aria-expanded="false" onclick="toggleReview(${i})">▸</button><button class="review-heading" onclick="toggleReview(${i})"><b>${reviewTitle(x)}</b><span>${x.customer||details.find(d=>d.label==='Manufacturer')?.value||'Imported business record'}</span></button><div class="actions">${closed?`<span class="tag">${x.ignored?'Ignored':'Resolved'}</span>`:`<button class="primary" onclick="editReview(${i})">Edit & Resolve</button><button onclick="approveUnknown(${i})">Keep Unknown</button><button class="danger" onclick="ignoreReview(${i})">Ignore</button>`}</div></div><div id="review-details-${i}" class="review-details" hidden>${details.map(d=>`<div><small>${d.label}</small><strong>${d.value}</strong></div>`).join('')}${x.resolution?`<div class="review-resolution"><small>Resolution</small><strong>${x.resolution}</strong></div>`:''}</div></div>`}).join('')}</div>`}

let reportPeriod='All Time';




const WARRANTY_STATUSES=['Reported','Replacement Sent','Submitted to Manufacturer','Approved','Credit Pending','Credit Applied','Denied','Closed'];
const PAYMENT_METHODS=['Cash','Venmo','PayPal','Zelle','Credit Card','Check','Bank Transfer','Customer Credit','Customer Refund','Other'];
function normName(x){return String(x||'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function manufacturers(){return [...new Set([...PRODUCTS.map(p=>p.maker),...db.orders.map(o=>o.maker)].filter(Boolean))].sort()}
function manufacturerField(value='vSeeBox'){return `<label class="field"><span>Manufacturer${help('Manufacturer')}</span><input name="maker" list="manufacturer-list" required value="${String(value).replace(/"/g,'&quot;')}"><datalist id="manufacturer-list">${manufacturers().map(x=>`<option value="${x}"></option>`).join('')}</datalist></label>`}
function relatedSales(customer){return db.sales.filter(s=>!s.voided&&(!customer||normName(s.customer)===normName(customer)))}
function customerMeta(name){db.settings=db.settings||{};db.settings.customers=db.settings.customers||{};return db.settings.customers[name]??={notes:'',tags:[],collections:[]}}
function editCustomerNotes(name){let m=customerMeta(name),notes=prompt('Customer notes',m.notes||'');if(notes===null)return;m.notes=notes;let tags=prompt('Customer tags, separated by commas',(m.tags||[]).join(', '));if(tags!==null)m.tags=tags.split(',').map(x=>x.trim()).filter(Boolean);saveLocal('Customer notes updated',name)}
function addCollectionNote(name){let method=prompt('Contact method or activity','Text sent');if(!method)return;let note=prompt('Collection note or payment promise');if(!note)return;customerMeta(name).collections.unshift({id:uid('COL'),date:today(),method,note});saveLocal('Collection note added',name+' · '+method)}
function addAttachment(recordType,recordId,e){let file=e.target.files?.[0];if(!file)return;if(file.size>1500000)return alert('Attachment must be smaller than 1.5 MB.');let reader=new FileReader();reader.onload=()=>{db.attachments=db.attachments||[];db.attachments.push({id:uid('ATT'),recordType,recordId,name:file.name,type:file.type,size:file.size,data:reader.result,date:new Date().toISOString()});saveLocal('Attachment added',recordType+' '+recordId+' · '+file.name)};reader.readAsDataURL(file);e.target.value=''}
function attachmentsView(type,id){let rows=(db.attachments||[]).filter(x=>x.recordType===type&&x.recordId===id);return `<div class="attachments">${rows.map(x=>`<a class="tag" href="${x.data}" download="${x.name}">${x.name}</a>`).join('')}<label class="btn">Attach File<input hidden type="file" onchange="addAttachment('${type}','${id}',event)"></label></div>`}
function repairProductionData(){let changed=[];let source=invoiceRows().find(x=>x.id==='INV-IMP-27a48fa912f1'),target=invoiceRows().find(x=>x.id==='INV-JASON-20260929-V6');if(source&&target&&target.balance>0&&source.balance<0){let amount=Math.min(Math.abs(source.balance),target.balance);db.payments.unshift({id:'PAY-JASON-CREDIT-REPAIR-290',saleId:target.id,date:today(),amount,method:'Customer Credit',creditSourceInvoice:source.id,creditAction:'Repair',notes:'Completed partially applied Jason Lohr correction'});db.payments.unshift({id:'CREDITUSE-JASON-REPAIR-290',saleId:source.id,date:today(),amount:-amount,method:'Credit Applied',creditTargetInvoice:target.id,creditAction:'Repair',notes:'Completed partially applied Jason Lohr correction'});changed.push(money(amount)+' Jason credit applied')}if(!db.adjustments.some(x=>x.id==='ADJ-LOST-STOLEN-20261001-V6')){db.adjustments.unshift({id:'ADJ-LOST-STOLEN-20261001-V6',productId:'p1',qty:-1,type:'Lost/Stolen',reason:'Lost/Stolen',date:today(),notes:'One vSeeBox V6 Plus confirmed lost or stolen by owner during inventory reconciliation',repairRecord:true});changed.push('one V6 Plus deducted as lost/stolen')}let claim=db.claims.find(c=>normName(c.customer).includes('lindsaybayouvista')),sale=db.sales.find(s=>normName(s.customer).includes('lindsaybayouvista'));if(claim&&sale){claim.customer=sale.customer;claim.relatedSaleId=sale.id;claim.status=WARRANTY_STATUSES.includes(claim.status)?claim.status:'Reported';changed.push('Lindsay warranty linked to '+sale.id)}if(changed.length){audit('v5.1 production repair',changed.join('; '));db.settings=db.settings||{};db.settings.v51RepairApplied=true;localStorage.setItem(LOCAL,JSON.stringify(db));if(token())cloudSave(true);render();alert('Repair completed:\n• '+changed.join('\n• '))}else alert('No remaining repair actions were needed.')}

function customerCredit(customer){return Math.max(0,-invoiceRows().filter(x=>x.customer===customer).reduce((n,x)=>n+x.balance,0))}
function creditInvoices(customer){return invoiceRows().filter(x=>x.customer===customer&&x.balance<-.009)}
function dueInvoices(customer){return invoiceRows().filter(x=>x.customer===customer&&x.balance>.009).sort((a,b)=>b.age-a.age)}
function useCreditPayment(sourceInvoice,targetInvoice,amount,action,note=''){let source=creditInvoices(db.sales.find(s=>s.id===sourceInvoice)?.customer||'').find(x=>x.id===sourceInvoice);let target=invoiceRows().find(x=>x.id===targetInvoice);amount=Math.min(Number(amount||0),source?Math.abs(source.balance):0,target?Math.max(0,target.balance):Infinity);if(!(amount>0))throw Error('No usable credit amount.');db.payments.unshift({id:uid('PAY'),saleId:targetInvoice,date:today(),amount,method:'Customer Credit',creditSourceInvoice:sourceInvoice,creditAction:action,notes:note});db.payments.unshift({id:uid('CREDITUSE'),saleId:sourceInvoice,date:today(),amount:-amount,method:'Credit Applied',creditTargetInvoice:targetInvoice,creditAction:action,notes:note});return amount}
function manageCredit(customer){let sources=creditInvoices(customer),credit=sources.reduce((n,x)=>n+Math.abs(x.balance),0);if(!credit)return alert('This customer has no available invoice credit.');let choice=prompt(`Available credit for ${customer}: ${money(credit)}\n\nAPPLY - outstanding invoice\nREFUND - money returned\nHOLD - future purchase`,'APPLY');if(!choice)return;choice=choice.trim().toUpperCase();let source=sources[0];if(choice==='APPLY'){let dues=dueInvoices(customer);if(!dues.length)return alert('No outstanding invoice for this customer.');let targetId=prompt('Invoice ID:\n'+dues.map(x=>x.id+' ('+money(x.balance)+' due)').join('\n'),dues[0].id),target=dues.find(x=>x.id===targetId);if(!target)return alert('Invoice not found.');let amount=Number(prompt('Credit amount',Math.min(Math.abs(source.balance),target.balance)));if(!(amount>0))return;let used=useCreditPayment(source.id,target.id,amount,'Applied to Invoice');saveLocal('Customer credit applied',customer+' · '+money(used))}else if(choice==='REFUND'){let amount=Math.min(Number(prompt('Refund amount',credit)),credit);if(!(amount>0))return;db.payments.unshift({id:uid('REFUND'),saleId:source.id,date:today(),amount:-amount,method:'Customer Refund',creditAction:'Refunded',notes:prompt('Refund reference','')||''});saveLocal('Customer credit refunded',customer+' · '+money(amount))}else if(choice==='HOLD'){db.sales.find(s=>s.id===source.id).creditHeld=true;saveLocal('Customer credit held',customer+' · '+money(credit))}else alert('Use APPLY, REFUND, or HOLD.')}
function adjustmentReasonOptions(){return ['Lost','Stolen','Warranty Replacement','Damaged','Demo','Found / Returned','Physical Count Correction','Other']}
function recordInventoryAdjustment(){let productName=prompt('Product:\n'+PRODUCTS.map((p,i)=>(i+1)+'. '+p.name).join('\n'),'vSeeBox V6 Plus');if(!productName)return;let product=normalizeProduct(productName);if(!product)return alert('Product not recognized.');let type=prompt('Adjustment reason:\n'+adjustmentReasonOptions().join('\n'),'Lost');if(!type)return;let qty=Number(prompt('Quantity to add or deduct. Use a negative number to deduct inventory.',type==='Found / Returned'?1:-1));if(!qty)return;let justification=prompt('Required justification or incident details');if(!justification||!justification.trim())return alert('A justification is required.');let a={id:uid('ADJ'),productId:product.id,qty,type,reason:type,date:today(),notes:justification.trim(),createdAt:new Date().toISOString()};db.adjustments.unshift(a);saveLocal('Inventory adjustment recorded',pname(product.id)+' · '+qty+' · '+type+' · '+justification.trim());if(type==='Warranty Replacement'&&confirm('Create a linked warranty claim now?')){page='Warranty';render()}}
function adjustmentLedger(){let rows=db.adjustments.filter(x=>!x.voided);return `<div class="card"><h3>Inventory Adjustment Ledger</h3><p class="muted">All manual additions and deductions require a reason and justification.</p><div class="actions"><button class="primary" onclick="recordInventoryAdjustment()">Record Inventory Adjustment</button></div>${empty(rows)}${rows.map(x=>`<div class="row"><div><b>${pname(x.productId)} · ${x.qty>0?'+':''}${x.qty}</b><p>${x.type||x.reason||'Adjustment'} · ${x.date||'Unknown date'} · ${x.notes||''}</p></div><span class="tag">${x.qty>0?'Added':'Deducted'}</span></div>`).join('')}</div>`}
function applyJasonCorrection(){let marker=db.history.some(x=>x.action==='Jason Lohr credit and inventory correction');if(marker)return alert('The Jason Lohr correction was already applied.');if(!confirm('Apply the approved Jason Lohr correction?\n\n• Apply $60 credit to the existing due invoice\n• Create a 09-29-2026 vSeeBox V6 Plus sale for $290\n• Apply the remaining $290 credit to that new sale\n• Record one additional V6 Plus as Lost/Stolen\n\nContinue?'))return;let customer='Jason Lohr',credits=creditInvoices(customer),dues=dueInvoices(customer);if(!credits.length)return alert('Jason Lohr credit invoice was not found.');let source=credits.sort((a,b)=>a.balance-b.balance)[0],due=dues.find(x=>Math.abs(x.balance-60)<.02)||dues[0];if(!due)return alert('Jason Lohr outstanding invoice was not found.');let first=Math.min(60,Math.abs(source.balance),due.balance);useCreditPayment(source.id,due.id,first,'Jason correction','Applied $60 to existing outstanding balance');let newSale={id:'INV-JASON-20260929-V6',date:'2026-09-29',customer,productId:'p1',qty:1,unitPrice:290,notes:'Created from remaining historical overpayment credit per owner correction',correctionRecord:true};db.sales.unshift(newSale);let remaining=customerCredit(customer);let used=useCreditPayment(source.id,newSale.id,Math.min(290,remaining),'Jason correction','Remaining credit applied to 09-29-2026 V6 Plus sale');db.adjustments.unshift({id:'ADJ-LOST-STOLEN-20261001-V6',productId:'p1',qty:-1,type:'Lost/Stolen',reason:'Lost/Stolen',date:today(),notes:'One vSeeBox V6 Plus confirmed lost or stolen by owner during inventory reconciliation',correctionRecord:true});audit('Jason Lohr credit and inventory correction',money(first)+' applied to '+due.id+'; '+money(used)+' applied to '+newSale.id+'; one V6 Plus deducted as lost/stolen');db.updatedAt=new Date().toISOString();localStorage.setItem(LOCAL,JSON.stringify(db));render();if(token())cloudSave(true);alert('Correction completed. Jason credit was applied, the 09-29-2026 sale was created and paid with credit, and one V6 Plus was deducted as lost/stolen.')}

const HELP={Customer:'Start typing to reuse an existing customer name. A new name creates a new customer automatically.',Product:'Choose the exact product sold so inventory and profit reports remain accurate.',Quantity:'Number of units in this transaction.',Date:'Transaction date used for aging and monthly reporting.','Unit Price':'Sale price per unit before payment activity.','Payment Received':'Money already collected for this sale. This may be zero or partial.','Payment Method':'How the payment was received.','Warranty Credit Applied':'Manufacturer credit used to reduce this purchase order.','Bank/Customs Fees':'Wire fees, customs, duties, or other costs required to receive inventory.',Shipping:'Freight or delivery cost associated with the transaction.','Approved Credit':'Amount the manufacturer approved for a future-order credit.','Replacement Cost':'Your product cost for the replacement unit.'};
function help(label){let x=HELP[label];return x?` <span class="help" tabindex="0" data-tip="${x.replace(/"/g,'&quot;')}">?</span>`:''}
function brandingLogo(){return db.settings?.brandLogo||'logo-placeholder.svg'}
function uploadBranding(e){let file=e.target.files?.[0];if(!file)return;if(!/^image\/(png|jpeg|webp|svg\+xml)$/.test(file.type))return alert('Use PNG, JPG, WEBP, or SVG.');if(file.size>2*1024*1024)return alert('Logo must be smaller than 2 MB.');let reader=new FileReader();reader.onload=()=>{db.settings=db.settings||{};db.settings.brandLogo=reader.result;db.settings.brandFileName=file.name;saveLocal('Branding logo updated',file.name)};reader.readAsDataURL(file)}
function resetBranding(){if(!confirm('Restore the default logo placeholder?'))return;db.settings=db.settings||{};delete db.settings.brandLogo;delete db.settings.brandFileName;saveLocal('Branding logo reset','Default placeholder')}
function downloadPartnerTemplate(){let a=document.createElement('a');a.href='partner-sales-template.csv';a.download='partner-sales-template.csv';a.click()}
function parseCSV(text){let rows=[],row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){let c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell.trim());cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell.trim());if(row.some(Boolean))rows.push(row);return rows}
function normalizeProduct(name){let q=String(name||'').trim().toLowerCase();let p=PRODUCTS.find(x=>x.name.toLowerCase()===q);if(!p)p=PRODUCTS.find(x=>q.includes(x.name.toLowerCase())||x.name.toLowerCase().includes(q));return p}
function importPartnerSales(e){let file=e.target.files?.[0];if(!file)return;let reader=new FileReader();reader.onload=()=>{try{let rows=parseCSV(reader.result);if(rows.length<2)throw Error('The file has no sales rows.');let headers=rows[0].map(x=>x.toLowerCase()),at=n=>headers.indexOf(n.toLowerCase()),required=['Sale Date','Customer','Product','Quantity','Unit Price'];for(let h of required)if(at(h)<0)throw Error('Missing required column: '+h);let added=0,skipped=0,errors=[];for(let i=1;i<rows.length;i++){let r=rows[i],date=r[at('Sale Date')]||'',customer=r[at('Customer')]||'',productName=r[at('Product')]||'',qty=Number(r[at('Quantity')]),price=Number(r[at('Unit Price')]),received=at('Payment Received')>=0?Number(r[at('Payment Received')]||0):0,method=at('Payment Method')>=0?r[at('Payment Method')]||'Other':'Other',notes=at('Notes')>=0?r[at('Notes')]||'':'',ref=at('Partner Reference')>=0?r[at('Partner Reference')]||'':'';let product=normalizeProduct(productName);if(!date||!customer||!product||!(qty>0)||!(price>=0)){errors.push('Row '+(i+1)+': invalid date, customer, product, quantity, or price');continue}let key=ref||[date,customer,product.id,qty,price].join('|'),duplicate=db.sales.some(s=>s.partnerImportKey===key);if(duplicate){skipped++;continue}let sale={id:'INV-PARTNER-'+Date.now()+'-'+i,date,customer,productId:product.id,qty,unitPrice:price,notes,partnerReference:ref,partnerImportKey:key,importedFromPartner:true};db.sales.unshift(sale);if(received>0)db.payments.unshift({id:uid('PAY'),saleId:sale.id,date,amount:received,method,notes:'Imported with partner sale'});added++}saveLocal('Partner sales import',file.name+' · '+added+' added · '+skipped+' duplicates skipped');alert(added+' sales added. '+skipped+' duplicates skipped.'+(errors.length?'\n\n'+errors.slice(0,10).join('\n'):''))}catch(err){alert('Partner sales import failed: '+err.message)}finally{e.target.value=''}};reader.readAsText(file)}
function invoiceHTML(id){let x=invoiceRows().find(x=>x.id===id);if(!x)return'';let logo=brandingLogo(),due=x.balance>0?x.balance:0,issued=x.date||today();return `<!doctype html><html><head><meta charset="utf-8"><title>Invoice ${x.id}</title><style>body{font-family:Arial,sans-serif;color:#111;padding:36px;max-width:850px;margin:auto}.head{display:flex;justify-content:space-between;border-bottom:3px solid #991b1b;padding-bottom:20px}.logo{max-width:100px;max-height:80px}.right{text-align:right}.box{margin-top:28px;border:1px solid #ccc;border-radius:8px;padding:18px}.line{display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid #ddd}.total{font-size:22px;font-weight:bold}.due{color:#991b1b}.note{margin-top:30px;color:#555}@media print{button{display:none}}</style></head><body><div class="head"><div><img class="logo" src="${logo}"><h2>Sickle &amp; Scythe</h2></div><div class="right"><h1>INVOICE</h1><div>${x.id}</div><div>Invoice date: ${issued}</div></div></div><div class="box"><b>Bill To</b><h3>${x.customer}</h3></div><div class="box"><div class="line"><b>Description</b><b>Amount</b></div><div class="line"><span>${pname(x.productId)} × ${x.qty}</span><span>${money(x.total)}</span></div><div class="line"><span>Payments received</span><span>(${money(x.paid)})</span></div><div class="line total due"><span>Balance due</span><span>${money(due)}</span></div></div><p class="note">Thank you for your business. Please reference invoice ${x.id} with payment.</p><button onclick="window.print()">Print / Save as PDF</button></body></html>`}
function createInvoice(id){let html=invoiceHTML(id),w=window.open('','_blank');if(!w)return alert('Allow popups to create the invoice.');w.document.open();w.document.write(html);w.document.close();setTimeout(()=>w.print(),400)}
function partnerSalesCard(){return `<div class="card"><h3>Sales Partner Import ${help('Payment Received')}</h3><p class="muted">Download the template, have the sales partner fill only the essential sale and payment fields, then upload the completed CSV. Imports append sales and never replace existing data. Partner Reference prevents duplicate imports.</p><div class="actions"><button onclick="downloadPartnerTemplate()">Download Sales Template</button><label class="btn primary">Upload Partner Sales CSV<input hidden type="file" accept=".csv,text/csv" onchange="importPartnerSales(event)"></label></div></div>`}

function lowThreshold(id){return Number(db.settings?.lowStock?.[id]??5)}
function lowStockRows(){return inventory().filter(x=>x.onHand<=lowThreshold(x.id))}
function setLowStock(id){let n=prompt('Low-stock threshold for '+pname(id),lowThreshold(id));if(n===null||isNaN(+n))return;db.settings=db.settings||{};db.settings.lowStock=db.settings.lowStock||{};db.settings.lowStock[id]=+n;saveLocal('Low-stock threshold updated',pname(id)+' · '+n)}
function integrityChecks(){let issues=[];for(let x of invoiceRows()){if(x.balance<-.009)issues.push({area:'Receivables',text:x.customer+' has '+money(Math.abs(x.balance))+' credit'});if(!x.date)issues.push({area:'Sales',text:x.id+' is missing a date'})}for(let p of inventory())if(p.onHand<0)issues.push({area:'Inventory',text:p.name+' has negative inventory: '+p.onHand});for(let o of db.orders)if((o.lines||[]).some(l=>Number(l.received||0)>Number(l.qty||0)))issues.push({area:'Purchase Orders',text:o.id+' has received quantity above ordered quantity'});for(let p of db.payments)if(!db.sales.some(s=>s.id===p.saleId))issues.push({area:'Payments',text:p.id+' is not linked to an invoice'});return issues}

function reviewHealth(area,text){if(area==='Receivables'){page='Receivables';arFilter=text.includes('credit')?'Credit':'Due';render();return}if(area==='Sales'){let id=(text.match(/INV-[^ ]+/)||[])[0];let sale=db.sales.find(s=>s.id===id);if(sale){let d=prompt('Enter the missing sale date (YYYY-MM-DD)',sale.date||'');if(d!==null&&d.trim()){sale.date=d.trim();saveLocal('Data health sale date corrected',id+' · '+d.trim())}}return}if(area==='Inventory'){page='Products';render();return}if(area==='Purchase Orders'){page='Purchase Orders';render();return}if(area==='Payments'){page='Sales & Payments';render();return}page='Needs Review';render()}
function reviewLowStock(id){page='Products';render();setTimeout(()=>setLowStock(id),0)}

function integrityView(){let issues=integrityChecks(),low=lowStockRows();return `<div class="card hero"><h1>Data Health</h1><p class="muted">Automated checks do not modify records.</p></div><div class="grid g3">${metric('Integrity Flags',issues.length)}${metric('Low-Stock Products',low.length)}${metric('Active Review Items',reviewRows().length)}</div><div class="card"><h3>Integrity Flags</h3>${empty(issues)}${issues.map(x=>`<div class="row"><div><b>${x.area}</b><p>${x.text}</p></div><button class="primary" onclick="reviewHealth('${x.area.replace(/'/g,"\'")}','${x.text.replace(/'/g,"\'")}')">Review</button></div>`).join('')}</div><div class="card"><h3>Low Stock</h3>${empty(low)}${low.map(x=>`<div class="row"><div><b>${x.name}</b><p>Threshold ${lowThreshold(x.id)} · ${x.onHand} on hand</p></div><button onclick="reviewLowStock('${x.id}')">Review Threshold</button></div>`).join('')}</div>`}
function universalSearch(){let q=globalQuery.trim().toLowerCase();if(!q)return'';let rows=[];for(let s of db.sales)if([s.id,s.customer,pname(s.productId),s.date].join(' ').toLowerCase().includes(q))rows.push({type:'Invoice',title:s.id+' · '+s.customer,detail:pname(s.productId)+' · '+(s.date||'Unknown date'),go:`openCustomer('${escAttr(s.customer)}')`});for(let o of db.orders)if([o.id,o.maker,o.status].join(' ').toLowerCase().includes(q))rows.push({type:'PO',title:o.id+' · '+o.maker,detail:o.status,go:"go('Purchase Orders')"});for(let e of db.expenses)if([e.vendor,e.category,e.date,e.notes].join(' ').toLowerCase().includes(q))rows.push({type:'Expense',title:e.vendor,detail:e.category+' · '+(e.date||'Unknown date'),go:"go('Expenses')"});for(let c of db.claims)if([c.customer,pname(c.productId),c.status].join(' ').toLowerCase().includes(q))rows.push({type:'Warranty',title:c.customer+' · '+pname(c.productId),detail:c.status,go:"go('Warranty')"});return `<div class="search-results card"><div class="row"><b>Search Results</b><button onclick="clearSearch()">Close</button></div>${empty(rows)}${rows.slice(0,30).map(x=>`<button class="search-hit" onclick="${x.go}"><span class="tag">${x.type}</span><b>${x.title}</b><small>${x.detail}</small></button>`).join('')}</div>`}
function setGlobalSearch(v){globalQuery=v;let host=document.querySelector('#search-host');if(host)host.innerHTML=universalSearch()} function clearSearch(){globalQuery='';let input=document.querySelector('.global-search');if(input){input.value='';input.focus()}let host=document.querySelector('#search-host');if(host)host.innerHTML=''}
async function cloudBackup(){try{if(!token())return alert('Connect OneDrive first.');let name='manual-backup-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json';await graph('/me/drive/special/approot:/'+name+':/content',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(db,null,2)});alert('Created OneDrive backup: '+name)}catch(e){alert('Backup failed: '+e.message)}}
function downloadJSON(){let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='sickle-scythe-full-backup-'+today()+'.json';a.click();URL.revokeObjectURL(url)}
function printReport(){window.print()}
function installApp(){if(deferredInstall){deferredInstall.prompt();deferredInstall.userChoice.finally(()=>deferredInstall=null)}else alert('Use your browser menu and choose Install app or Add to Home Screen.')}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e})


function poSubtotal(o){return (o.lines||[]).reduce((n,l)=>n+Number(l.qty||0)*Number(l.unitCost||0),0)}
function poTotal(o){return poSubtotal(o)+Number(o.shipping||0)+Number(o.fees||0)-Number(o.credit||0)}
function weightedCosts(){let out={};for(let p of PRODUCTS){let units=0,cost=0;for(let o of db.orders.filter(o=>!o.cancelled)){let subtotal=poSubtotal(o);for(let l of (o.lines||[]).filter(l=>l.productId===p.id)){let received=Number(l.received||0),base=received*Number(l.unitCost||0),share=subtotal>0?(Number(l.qty||0)*Number(l.unitCost||0))/subtotal:0,landed=base+(Number(o.shipping||0)+Number(o.fees||0)-Number(o.credit||0))*share*(Number(l.qty||0)?received/Number(l.qty):0);units+=received;cost+=landed}}out[p.id]=units>0?cost/units:p.cost}return out}
function csvCell(v){let x=v==null?'':String(v);return '"'+x.replace(/"/g,'""')+'"'}
function downloadCSV(name,headers,rows){let csv=[headers.map(csvCell).join(','),...rows.map(r=>r.map(csvCell).join(','))].join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name+'-'+today()+'.csv';a.click();URL.revokeObjectURL(url)}
function exportSales(){let wc=weightedCosts();downloadCSV('sales',['Invoice','Date','Customer','Product','Quantity','Unit Price','Revenue','Weighted Unit Cost','COGS','Gross Profit','Balance'],invoiceRows().map(x=>[x.id,x.date,x.customer,pname(x.productId),x.qty,x.unitPrice,x.total,wc[x.productId],x.qty*wc[x.productId],x.total-x.qty*wc[x.productId],x.balance]))}
function exportPayments(){downloadCSV('payments',['Payment ID','Invoice','Date','Method','Amount','Voided'],db.payments.map(x=>[x.id,x.saleId,x.date,x.method,x.amount,!!x.voided]))}
function exportExpenses(){downloadCSV('expenses',['Expense ID','Date','Vendor','Category','Tax Category','Amount','Method','Receipt Status','Notes','Voided'],db.expenses.map(x=>[x.id,x.date,x.vendor,x.category,x.taxCategory||'',x.amount,x.method||'',x.receiptStatus||'',x.notes||'',!!x.voided]))}
function exportInventory(){let wc=weightedCosts();downloadCSV('inventory',['Product','Manufacturer','On Hand','Weighted Landed Unit Cost','Inventory Value','Default Retail'],inventory().map(x=>[x.name,x.maker,x.onHand,wc[x.id],Math.max(0,x.onHand)*wc[x.id],x.retail]))}
function exportReceivables(){downloadCSV('receivables',['Invoice','Customer','Date','Age Bucket','Invoice Total','Paid','Balance','Status'],invoiceRows().filter(x=>Math.abs(x.balance)>.009).map(x=>[x.id,x.customer,x.date,x.bucket,x.total,x.paid,x.balance,x.status]))}
function exportWarranty(){downloadCSV('warranty',['Claim ID','Date','Customer','Product','Status','Replacement Cost','Shipping','Approved Credit','Applied Credit','Remaining Credit'],db.claims.map(x=>[x.id,x.date,x.customer,pname(x.productId),x.status,x.replacementCost,x.shipping,x.approvedCredit,x.appliedCredit,Number(x.approvedCredit||0)-Number(x.appliedCredit||0)]))}
function accountantExports(){return `<div class="card"><h3>Accountant Exports</h3><p class="muted">CSV files open in Excel and use the current OneDrive production database.</p><div class="actions"><button onclick="exportSales()">Sales & Profit</button><button onclick="exportPayments()">Payments</button><button onclick="exportExpenses()">Expenses</button><button onclick="exportInventory()">Inventory Valuation</button><button onclick="exportReceivables()">Receivables</button><button onclick="exportWarranty()">Warranty Credits</button></div></div>`}

function validDate(v){let d=v?new Date(v+'T00:00:00'):null;return d&&!isNaN(d)?d:null}
function periodMatch(date,period=reportPeriod){if(period==='All Time')return true;let d=validDate(date);if(!d)return false;let now=new Date();return period==='This Month'?d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth():period==='This Year'?d.getFullYear()===now.getFullYear():true}
function unitCount(sales){return sales.reduce((n,s)=>n+Number(s.qty||0),0)}
function transactionCount(sales){return sales.length}
function financials(period='All Time'){let sales=db.sales.filter(s=>!s.voided&&periodMatch(s.date,period)),ids=new Set(sales.map(s=>s.id)),payments=db.payments.filter(p=>!p.voided&&ids.has(p.saleId)&&periodMatch(p.date||'',period)),expenses=db.expenses.filter(e=>!e.voided&&periodMatch(e.date,period)),revenue=sales.reduce((n,s)=>n+Number(s.qty||0)*Number(s.unitPrice||0),0),wc=weightedCosts(),cogs=sales.reduce((n,s)=>n+Number(s.qty||0)*(wc[s.productId]||0),0),collected=payments.reduce((n,p)=>n+Number(p.amount||0),0),expenseTotal=expenses.reduce((n,e)=>n+Number(e.amount||0),0);return{sales,payments,expenses,revenue,cogs,collected,expenseTotal,unitsSold:unitCount(sales),salesTransactions:transactionCount(sales),gross:revenue-cogs,net:revenue-cogs-expenseTotal}}
function monthKey(date){let d=validDate(date);return d?d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0'):'Unknown'}
function monthlyTrend(){let map={};for(let s of db.sales.filter(s=>!s.voided)){let k=monthKey(s.date);if(k==='Unknown')continue;(map[k]??={revenue:0,collected:0}).revenue+=Number(s.qty||0)*Number(s.unitPrice||0)}for(let p of db.payments.filter(p=>!p.voided)){let k=monthKey(p.date);if(k==='Unknown')continue;(map[k]??={revenue:0,collected:0}).collected+=Number(p.amount||0)}return Object.entries(map).sort((a,b)=>a[0].localeCompare(b[0])).slice(-12).map(([month,x])=>({month,...x}))}
function arAging(){let out={'0-30 Days':0,'31-60 Days':0,'61-90 Days':0,'90+ Days':0,'Unknown Date':0,'Customer Credits':0};for(let x of invoiceRows()){if(x.balance<-.009)out['Customer Credits']+=Math.abs(x.balance);else if(x.balance>.009)out[x.bucket]+=x.balance}return out}
function topCustomers(){let map={};for(let s of db.sales.filter(s=>!s.voided)){let x=map[s.customer]??={customer:s.customer,revenue:0,units:0};x.revenue+=Number(s.qty||0)*Number(s.unitPrice||0);x.units+=Number(s.qty||0)}return Object.values(map).sort((a,b)=>b.revenue-a.revenue).slice(0,8)}
function productPerformance(){let wc=weightedCosts();return PRODUCTS.map(p=>{let ss=db.sales.filter(s=>!s.voided&&s.productId===p.id),units=ss.reduce((n,s)=>n+Number(s.qty||0),0),revenue=ss.reduce((n,s)=>n+Number(s.qty||0)*Number(s.unitPrice||0),0);return{...p,weightedCost:wc[p.id],units,revenue,gross:revenue-units*wc[p.id],onHand:inventory().find(x=>x.id===p.id)?.onHand||0}}).sort((a,b)=>b.revenue-a.revenue)}
function forecastRows(){let cutoff=new Date();cutoff.setDate(cutoff.getDate()-90);return inventory().map(p=>{let sold90=db.sales.filter(s=>!s.voided&&s.productId===p.id&&validDate(s.date)&&validDate(s.date)>=cutoff).reduce((n,s)=>n+Number(s.qty||0),0),monthly=sold90/3,months=monthly>0?p.onHand/monthly:null;return{...p,sold90,monthly,months}})}
function barRows(rows,label,value,format=money){let max=Math.max(1,...rows.map(value));return rows.map(x=>`<div class="chart-row"><div class="chart-label">${label(x)}</div><div class="chart-track"><div class="chart-fill" style="width:${Math.max(2,value(x)/max*100)}%"></div></div><strong>${format(value(x))}</strong></div>`).join('')}
function dashboardView(){let all=financials(),month=financials('This Month'),aging=arAging(),trend=monthlyTrend(),tops=topCustomers(),forecast=forecastRows(),t=totals();return `<div class="card hero"><h1>Business Overview</h1><p class="muted">Production KPIs from the OneDrive database. Historical rows without dates remain included in All Time values.</p></div><div class="grid g4">${metric('All-Time Revenue',money(all.revenue))}${metric('Units Sold',all.unitsSold)}${metric('Sales Transactions',all.salesTransactions)}${metric('Cash Collected',money(all.collected))}${metric('Outstanding A/R',money(t.ar))}${metric('Estimated Net Profit',money(all.net))}${metric('Inventory On Hand',t.onHand+' units')}${metric('Inventory Value',money(t.invValue))}${metric('This Month Revenue',money(month.revenue))}${metric('Manufacturer Credits',money(t.credit))}</div><div class="grid g2"><div class="card"><h3>Receivables Aging</h3>${Object.entries(aging).map(([k,v])=>`<div class="row"><span>${k}</span><strong>${money(v)}</strong></div>`).join('')}</div><div class="card"><h3>Inventory Forecast</h3>${forecast.map(x=>`<div class="row"><div><b>${x.name}</b><p>${x.sold90} sold in last 90 days · ${x.monthly.toFixed(1)}/month</p></div><span class="tag">${x.months===null?'No recent velocity':x.months<0?'Review count':x.months.toFixed(1)+' months'}</span></div>`).join('')}</div></div><div class="grid g2"><div class="card"><h3>Monthly Revenue</h3>${trend.length?barRows(trend,x=>x.month,x=>x.revenue):'<p class="muted">No dated sales available.</p>'}</div><div class="card"><h3>Top Customers</h3>${barRows(tops,x=>x.customer,x=>x.revenue)}</div></div>`}
function setReportPeriod(x){reportPeriod=x;render()}
function reportsView(){let f=financials(),aging=arAging(),products=productPerformance(),trend=monthlyTrend(),periods=['All Time','This Year','This Month'];return `<div class="card hero"><h1>Operational Reports</h1><div class="actions"><button onclick="printReport()">Print / Save PDF</button>${periods.map(x=>`<button class="${reportPeriod===x?'active':''}" onclick="setReportPeriod('${x}')">${x}</button>`).join('')}</div></div><div class="grid g4">${metric('Revenue',money(f.revenue))}${metric('Collected',money(f.collected))}${metric('COGS Estimate',money(f.cogs))}${metric('Gross Profit',money(f.gross))}${metric('Expenses',money(f.expenseTotal))}${metric('Estimated Net Profit',money(f.net))}${metric('Units Sold',f.unitsSold)}${metric('Sales Transactions',f.salesTransactions)}${metric('Payments Count',f.payments.length)}</div><div class="grid g2"><div class="card"><h3>Product Performance</h3>${products.map(x=>`<div class="row"><div><b>${x.name}</b><p>${x.units} sold · ${x.onHand} on hand · ${money(x.weightedCost)} landed/unit</p></div><div><strong>${money(x.revenue)}</strong><p>${money(x.gross)} gross estimate</p></div></div>`).join('')}</div><div class="card"><h3>A/R Aging</h3>${Object.entries(aging).map(([k,v])=>`<div class="row"><span>${k}</span><strong>${money(v)}</strong></div>`).join('')}</div></div><div class="card"><h3>12-Month Revenue Trend</h3>${trend.length?barRows(trend,x=>x.month,x=>x.revenue):'<p class="muted">No dated sales available.</p>'}</div>${accountantExports()}`}

function render(){let t=totals(),body='';if(page==='Dashboard')body=dashboardView();
else if(page==='Products')body=`<div class="grid g2">${inventory().map(p=>`<div class="card"><span class="tag">${p.maker}</span><h3>${p.name}</h3><div class="grid g3">${metric('On hand',p.onHand)}${metric('Cost',money(p.cost))}${metric('Retail',money(p.retail))}</div><div class="actions"><span class="tag">Low-stock threshold: ${lowThreshold(p.id)}</span><button onclick="setLowStock('${p.id}')">Set Threshold</button></div></div>`).join('')}</div>${adjustmentLedger()}`;
else if(page==='Purchase Orders')body=ordersView();else if(page==='Receivables')body=receivablesView();else if(page==='Sales & Payments')body=salesView();else if(page==='Customers')body=customersView();else if(page==='Expenses')body=expensesView();else if(page==='Warranty')body=warrantyView();else if(page==='Reports')body=reportsView();else if(page==='Needs Review')body=needsReviewView();else if(page==='Data Health')body=integrityView();else if(page==='History')body=`<div class="card">${empty(db.history)}${db.history.map(h=>`<div class="row"><div><b>${h.action}</b><p>${new Date(h.date).toLocaleString()}</p></div><span>${h.detail}</span></div>`).join('')}</div>`;else body=settingsView();$('#app').innerHTML=shell(body)} function go(p){page=p;render();if(page==='Purchase Orders'&&!document.querySelector('.po-line'))addPOLine()}
function ordersView(){return `<div class="card"><h3>Create Multi-line Purchase Order</h3><form id="po"><div class="fields">${manufacturerField()}${field('ETA','eta','date',today())}${field('Shipping','shipping','number',0)}${field('Bank/Customs Fees','fees','number',0)}${field('Warranty Credit Applied','credit','number',0)}</div><div id="polines"></div><div class="actions"><button type="button" onclick="addPOLine()">Add Product Line</button><button class="primary">Save Purchase Order</button></div></form></div><div class="card"><h3>Purchase Orders</h3>${empty(db.orders)}${db.orders.map(o=>`<div class="row"><div><b>${o.id} · ${o.maker}</b><p>${o.lines.map(l=>l.qty+' × '+pname(l.productId)).join(', ')} · ${o.status}</p>${attachmentsView('purchase-order',o.id)}<p> · Subtotal ${money(poSubtotal(o))} · Freight/Fees ${money(Number(o.shipping||0)+Number(o.fees||0))} · Credit ${money(o.credit||0)} · Paid ${money(poTotal(o))}</p></div><div class="actions"><span class="tag">${o.cancelled?'Cancelled':o.status}</span><button onclick="editPO('${o.id}')">Edit</button>${!o.cancelled&&o.status!=='Received'?`<button onclick="receivePO('${o.id}')">Receive</button>`:''}${!o.cancelled?`<button class="danger" onclick="cancelPO('${o.id}')">Cancel</button>`:''}</div></div>`).join('')}</div>`}
function addPOLine(){let d=document.createElement('div');d.className='fields po-line';d.innerHTML=select('Product','lineProduct',PRODUCTS.map(p=>[p.id,p.name]))+field('Quantity','lineQty','number',1)+field('Unit Cost','lineCost','number',200)+`<div class="actions"><button type="button" onclick="this.closest('.po-line').remove()">Remove</button></div>`;$('#polines').appendChild(d)}
function salesView(){return `${partnerSalesCard()}<div class="card"><h3>Record Sale</h3><form id="sale"><div class="fields">${customerField()}${select('Product','productId',PRODUCTS.map(p=>[p.id,p.name]))}${field('Quantity','qty','number',1)}${field('Unit Price','unitPrice','number',265)}${field('Date','date','date',today())}</div><button class="primary">Save Sale</button></form></div><div class="card"><h3>Invoices</h3>${empty(db.sales)}${db.sales.map(s=>{let paid=db.payments.filter(p=>!p.voided&&p.saleId===s.id).reduce((n,p)=>n+p.amount,0),bal=s.qty*s.unitPrice-paid;return `<div class="row"><div><b>${s.id} · ${s.customer}</b><p>${pname(s.productId)} · ${money(paid)} paid</p></div><div><span class="tag">${money(bal)} due</span> <button onclick="editSale('${s.id}')">Edit</button>${!s.voided?`<button class="danger" onclick="voidSale('${s.id}')">Void</button>`:''} ${bal>0?`<button onclick="createInvoice('${s.id}')">Invoice / PDF</button><button onclick="pay('${s.id}',${bal})">Payment</button>`:''}</div></div>`}).join('')}</div><div class="card"><h3>Payment History</h3>${empty(db.payments)}${db.payments.map(p=>`<div class="row"><div><b>${p.saleId} · ${p.method||'Other'}</b><p>${p.date}</p></div><div class="actions"><strong>${money(p.amount)}</strong><button onclick="editPayment('${p.id}')">Edit</button>${!p.voided?`<button class="danger" onclick="voidPayment('${p.id}')">Void</button>`:''}</div></div>`).join('')}</div>`}
function customersView(){if(selectedCustomer)return customerDetail(selectedCustomer);let names=[...new Set(db.sales.filter(s=>!s.voided).map(s=>s.customer))],rows=names.map(n=>{let ss=invoiceRows().filter(x=>x.customer===n),balance=ss.reduce((a,x)=>a+x.balance,0),paid=ss.reduce((a,x)=>a+x.paid,0);return{name:n,count:ss.length,units:unitCount(ss),balance,paid}}).sort((a,b)=>(a.balance<0?0:a.balance>0?1:2)-(b.balance<0?0:b.balance>0?1:2)||Math.abs(b.balance)-Math.abs(a.balance));return `<div class="card">${empty(rows)}${rows.map(x=>`<div class="row"><div><b>${x.name}</b><p>${x.count} invoices · ${x.units} units · ${money(x.paid)} paid</p></div><div class="actions"><span class="tag">${x.balance<0?money(Math.abs(x.balance))+' credit':money(x.balance)+' due'}</span><button onclick="openCustomer('${escAttr(x.name)}')">Open Profile</button></div></div>`).join('')}</div>`}
function expensesView(){return `<div class="card"><h3>Add Expense</h3><form id="expense"><div class="fields">${field('Vendor','vendor')}${field('Category','category','text','Shipping')}${field('Amount','amount','number',0)}${field('Date','date','date',today())}</div><button class="primary">Save Expense</button></form></div><div class="card">${empty(db.expenses)}${db.expenses.map(e=>`<div class="row"><div><b>${e.vendor}</b><p>${e.category} · ${e.date}</p>${attachmentsView('expense',e.id)}</div><div class="actions"><strong>${money(e.amount)}</strong><button onclick="editExpense('${e.id}')">Edit</button>${!e.voided?`<button class="danger" onclick="voidExpense('${e.id}')">Void</button>`:''}</div></div>`).join('')}</div>`}
function warrantyView(){return `<div class="card"><h3>Warranty Claim</h3><form id="claim"><div class="fields">${customerField()}${select('Product','productId',PRODUCTS.map(p=>[p.id,p.name]))}${field('Quantity','qty','number',1)}${field('Replacement Cost','replacementCost','number',200)}${field('Shipping','shipping','number',0)}${field('Approved Credit','approvedCredit','number',0)}${field('Date','date','date',today())}${select('Status','status',WARRANTY_STATUSES.map(x=>[x,x]))}${select('Related Sale','relatedSaleId',[['','None'],...db.sales.filter(s=>!s.voided).map(s=>[s.id,s.customer+' · '+s.id+' · '+pname(s.productId)])])}</div><button class="primary">Save Claim</button></form></div><div class="card">${empty(db.claims)}${db.claims.map(c=>`<div class="row"><div><b>${c.customer} · ${pname(c.productId)}</b><p>${c.status} · Cost ${money(c.replacementCost+c.shipping)}${c.relatedSaleId?' · Sale '+c.relatedSaleId:''}</p>${attachmentsView('warranty',c.id)}</div><div class="actions"><strong>${money(c.approvedCredit-c.appliedCredit)} credit</strong><button onclick="editClaim('${c.id}')">Edit</button>${!c.voided?`<button class="danger" onclick="voidClaim('${c.id}')">Void</button>`:''}</div></div>`).join('')}</div>`}
function settingsView(){return `<div class="grid g2"><div class="card"><h3>Microsoft OneDrive</h3><p class="muted">The private App Folder is the single source of truth. Local storage remains an offline cache.</p><div class="actions">${token()?`<button onclick="cloudLoad()">Load Cloud</button><button onclick="cloudSave()">Save Cloud</button><button class="primary" onclick="reconnect()">Reconnect Microsoft Account</button><button class="danger" onclick="signOut()">Sign Out</button>`:`<button class="primary" onclick="signIn()">Sign in with Microsoft</button>`}</div></div>${accountantExports()}<div class="card"><h3>Backup & Recovery</h3><p class="muted">Create a timestamped OneDrive backup or download the full database.</p><div class="actions"><button onclick="cloudBackup()">Create OneDrive Backup</button><button onclick="downloadJSON()">Download Full JSON</button></div></div><div class="card"><h3>Install App</h3><p class="muted">Install the PWA on this device for a home-screen or desktop icon.</p><button class="primary" onclick="installApp()">Install App</button></div><div class="card"><h3>Branding</h3><p class="muted">Upload a logo used in the application and generated invoices. The image is stored inside the private OneDrive database and follows every device.</p><div class="brand-preview"><img src="${brandingLogo()}"><div><b>${db.settings?.brandFileName||'Default placeholder'}</b><p class="muted">PNG, JPG, WEBP, or SVG. Maximum 2 MB.</p></div></div><div class="actions"><label class="btn primary">Upload / Change Logo<input hidden type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onchange="uploadBranding(event)"></label><button onclick="resetBranding()">Restore Default</button></div></div></div>`}
function formData(id){return Object.fromEntries(new FormData($(id)).entries())}
document.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='po'){let f=formData('#po');if(!f.maker||!f.maker.trim())return alert('Manufacturer is required.');let lines=[...document.querySelectorAll('.po-line')].map(x=>({productId:x.querySelector('[name=lineProduct]').value,qty:+x.querySelector('[name=lineQty]').value,unitCost:+x.querySelector('[name=lineCost]').value,received:0})).filter(x=>x.productId&&x.qty>0);if(!lines.length)return alert('Add at least one product line with a quantity greater than zero.');let applied=Math.max(0,+f.credit),remaining=applied;for(const c of db.claims.filter(c=>!c.voided&&PRODUCTS.find(p=>p.id===c.productId)?.maker===f.maker&&c.approvedCredit>c.appliedCredit)){let use=Math.min(remaining,c.approvedCredit-c.appliedCredit);c.appliedCredit+=use;remaining-=use;if(!remaining)break}let actualApplied=applied-remaining;db.orders.unshift({id:'PO-'+new Date().getFullYear()+'-'+String(db.orders.length+1).padStart(3,'0'),maker:f.maker,eta:f.eta,shipping:+f.shipping,fees:+f.fees,credit:actualApplied,lines,status:'Ordered'});saveLocal('Purchase order created',db.orders[0].id+' · credit '+money(actualApplied))}if(e.target.id==='sale'){let f=formData('#sale');if(!f.customer||!f.productId||!f.date||!(+f.qty>0)||!(+f.unitPrice>=0))return alert('Customer, product, date, quantity, and unit price are required.');f.id='INV-'+(1001+db.sales.length);f.qty=+f.qty;f.unitPrice=+f.unitPrice;db.sales.unshift(f);saveLocal('Sale created',f.id)}if(e.target.id==='expense'){let f=formData('#expense');f.id=uid('EXP');f.amount=+f.amount;db.expenses.unshift(f);saveLocal('Expense created',f.vendor)}if(e.target.id==='claim'){let f=formData('#claim');if(!f.customer||!f.productId||!f.date||!WARRANTY_STATUSES.includes(f.status))return alert('Customer, product, date, and a valid status are required.');Object.assign(f,{id:uid('WR'),qty:+f.qty,replacementCost:+f.replacementCost,shipping:+f.shipping,approvedCredit:+f.approvedCredit,appliedCredit:0,replacementSent:f.status==='Replacement Sent'});db.claims.unshift(f);saveLocal('Warranty claim created',f.customer)}});
function editPO(id){let o=db.orders.find(x=>x.id===id);if(!o)return;let maker=prompt('Manufacturer',o.maker);if(maker===null)return;let eta=prompt('ETA (YYYY-MM-DD)',o.eta);if(eta===null)return;let shipping=prompt('Shipping',o.shipping);if(shipping===null)return;let fees=prompt('Bank/Customs Fees',o.fees);if(fees===null)return;let credit=prompt('Warranty Credit Applied',o.credit);if(credit===null)return;o.maker=maker;o.eta=eta;o.shipping=+shipping;o.fees=+fees;o.credit=+credit;for(const l of o.lines){let q=prompt('Quantity for '+pname(l.productId),l.qty);if(q===null)continue;let c=prompt('Unit cost for '+pname(l.productId),l.unitCost);if(c===null)continue;l.qty=+q;l.unitCost=+c;if(l.received>l.qty)l.received=l.qty}saveLocal('Purchase order edited',id)}
function editSale(id){let s=db.sales.find(x=>x.id===id);if(!s)return;let customer=prompt('Customer',s.customer);if(customer===null)return;let qty=prompt('Quantity',s.qty);if(qty===null)return;let price=prompt('Unit Price',s.unitPrice);if(price===null)return;let date=prompt('Sale Date (YYYY-MM-DD)',s.date);if(date===null)return;s.customer=customer;s.qty=+qty;s.unitPrice=+price;s.date=date;saveLocal('Sale edited',id)}
function editExpense(id){let e=db.expenses.find(x=>x.id===id);if(!e)return;let vendor=prompt('Vendor',e.vendor);if(vendor===null)return;let category=prompt('Category',e.category);if(category===null)return;let amount=prompt('Amount',e.amount);if(amount===null)return;let date=prompt('Date (YYYY-MM-DD)',e.date);if(date===null)return;e.vendor=vendor;e.category=category;e.amount=+amount;e.date=date;saveLocal('Expense edited',id)}
function editClaim(id){let c=db.claims.find(x=>x.id===id);if(!c)return;let customer=prompt('Customer',c.customer);if(customer===null)return;let cost=prompt('Replacement Cost',c.replacementCost);if(cost===null)return;let shipping=prompt('Shipping',c.shipping);if(shipping===null)return;let credit=prompt('Approved Credit',c.approvedCredit);if(credit===null)return;let status=prompt('Status: '+WARRANTY_STATUSES.join(', '),c.status);if(status===null)return;if(!WARRANTY_STATUSES.includes(status))return alert('Choose an allowed warranty status.');let related=prompt('Related sale ID',c.relatedSaleId||'');c.customer=customer;c.replacementCost=+cost;c.shipping=+shipping;c.approvedCredit=+credit;c.status=status;c.relatedSaleId=related;saveLocal('Warranty claim edited',id)}
function editPayment(id){let p=db.payments.find(x=>x.id===id);if(!p)return;let amount=prompt('Payment Amount',p.amount);if(amount===null)return;let method=prompt('Payment Method: '+PAYMENT_METHODS.join(', '),p.method||'Other');if(method===null)return;if(!PAYMENT_METHODS.includes(method))return alert('Choose an allowed payment method.');let date=prompt('Payment Date (YYYY-MM-DD)',p.date);if(date===null)return;p.amount=+amount;p.method=method;p.date=date;saveLocal('Payment edited',id)}
function receivePO(id){let o=db.orders.find(x=>x.id===id);if(!o||o.cancelled)return;let changed=false;for(const l of o.lines){let remaining=Math.max(0,l.qty-(l.received||0));if(!remaining)continue;let q=prompt('Receive quantity for '+pname(l.productId)+' (remaining '+remaining+')',remaining);if(q===null)continue;q=Math.max(0,Math.min(+q,remaining));if(q){l.received=(l.received||0)+q;changed=true}}if(!changed)return;let done=o.lines.every(l=>(l.received||0)>=l.qty),any=o.lines.some(l=>(l.received||0)>0);o.status=done?'Received':any?'Partially Received':'Ordered';saveLocal('Inventory received',id+' · '+o.status)}
function reason(label){let r=prompt(label+' reason');return r&&r.trim()?r.trim():null}
function cancelPO(id){let r=reason('Cancellation');if(!r)return;let o=db.orders.find(x=>x.id===id);o.cancelled=true;o.cancelReason=r;o.status='Cancelled';saveLocal('Purchase order cancelled',id+' · '+r)}
function voidSale(id){let r=reason('Void sale');if(!r)return;let x=db.sales.find(s=>s.id===id);x.voided=true;x.voidReason=r;saveLocal('Sale voided',id+' · '+r)}
function voidPayment(id){let r=reason('Void payment');if(!r)return;let x=db.payments.find(p=>p.id===id);x.voided=true;x.voidReason=r;saveLocal('Payment voided',id+' · '+r)}
function voidExpense(id){let r=reason('Void expense');if(!r)return;let x=db.expenses.find(e=>e.id===id);x.voided=true;x.voidReason=r;saveLocal('Expense voided',id+' · '+r)}
function voidClaim(id){let r=reason('Void warranty claim');if(!r)return;let x=db.claims.find(c=>c.id===id);x.voided=true;x.voidReason=r;saveLocal('Warranty claim voided',id+' · '+r)}
 function pay(id,max){let a=+prompt('Payment amount',max);if(!a)return;let method=prompt('Payment method: '+PAYMENT_METHODS.join(', '),'Cash')||'Other';if(!PAYMENT_METHODS.includes(method))return alert('Choose an allowed payment method.');db.payments.unshift({id:uid('PAY'),saleId:id,amount:Math.min(a,max),method,date:today()});saveLocal('Payment received',id+' '+money(a))} function reconnect(){localStorage.removeItem('ss_tokens');sessionStorage.removeItem('pkce');sessionStorage.removeItem('state');signIn()} function signOut(){localStorage.removeItem('ss_tokens');sessionStorage.removeItem('pkce');sessionStorage.removeItem('state');render()} window.toggleReview=toggleReview;window.reviewStatusFilter=reviewStatusFilter;window.repairProductionData=repairProductionData;window.editCustomerNotes=editCustomerNotes;window.addCollectionNote=addCollectionNote;window.addAttachment=addAttachment;window.manageCredit=manageCredit;window.recordInventoryAdjustment=recordInventoryAdjustment;window.applyJasonCorrection=applyJasonCorrection;window.reviewHealth=reviewHealth;window.reviewLowStock=reviewLowStock;window.uploadBranding=uploadBranding;window.resetBranding=resetBranding;window.downloadPartnerTemplate=downloadPartnerTemplate;window.importPartnerSales=importPartnerSales;window.createInvoice=createInvoice;window.setGlobalSearch=setGlobalSearch;window.clearSearch=clearSearch;window.setLowStock=setLowStock;window.cloudBackup=cloudBackup;window.downloadJSON=downloadJSON;window.printReport=printReport;window.installApp=installApp;window.exportSales=exportSales;window.exportPayments=exportPayments;window.exportExpenses=exportExpenses;window.exportInventory=exportInventory;window.exportReceivables=exportReceivables;window.exportWarranty=exportWarranty;window.setReportPeriod=setReportPeriod;window.setARFilter=setARFilter;window.openCustomer=openCustomer;window.closeCustomer=closeCustomer;window.editReview=editReview;window.approveUnknown=approveUnknown;window.ignoreReview=ignoreReview;window.go=go;window.addPOLine=addPOLine;window.cancelPO=cancelPO;window.voidSale=voidSale;window.voidPayment=voidPayment;window.voidExpense=voidExpense;window.voidClaim=voidClaim;window.editPO=editPO;window.editSale=editSale;window.editExpense=editExpense;window.editClaim=editClaim;window.editPayment=editPayment;window.receivePO=receivePO;window.pay=pay;window.cloudLoad=cloudLoad;window.cloudSave=cloudSave;window.signIn=signIn;window.reconnect=reconnect;window.signOut=signOut;
render();if(page==='Purchase Orders')addPOLine();callback().catch(e=>alert(e.message));